const SOCKET_URL = {
    SERVER_SEND_COUNT_LIKE: 'SERVER-SEND-COUNT-LIKE',
    CLIENT_SEND_COUNT_LIKE: 'CLIENT-SEND-COUNT-LIKE',
    CLIENT_SEND_COUNT_COMMENT: 'CLIENT-SEND-COUNT-COMMENT',
    SERVER_SEND_COUNT_COMMENT: 'SERVER-SEND-COUNT-COMMENT',
}

export default SOCKET_URL