const SOCKET_URL = {
    SERVER_SEND_COUNT_LIKE: 'SERVER-SEND-COUNT-LIKE',
    CLIENT_SEND_COUNT_LIKE: 'CLIENT-SEND-COUNT-LIKE',
    CLIENT_SEND_COUNT_COMMENT: 'CLIENT-SEND-COUNT-COMMENT',
    SERVER_SEND_COUNT_COMMENT: 'SERVER-SEND-COUNT-COMMENT',
    CLIENT_SEND_MESSAGE: 'CLIENT-SEND-MESSAGE',
    SERVER_SEND_MESSAGE: 'SERVER-SEND-MESSAGE',
    CLIENT_SEND_ROOM: 'CLIENT-SEND-ROOM',
}

export default SOCKET_URL